### ISSUE TITLE
Possible to select the same token in the From to Fields

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2708]
1. Open https://swap.cow.fi/#/1/swap/WETH/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2?sellAmount=1
2. Check the form

**AR**: the same token is displayed in the from/to fields (a token name and its address in the URL)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/1f005fef-366c-4359-916d-371d5c80298e)
**ER**: impossible to pick the same token

**Comment by Wholesomebruh** [comment]
Hey, looks like issue is already resolved. On trying to set same token in to and from input box , it's taking the token in one box and asking to select token in other one and if there are already two different tokens present , it's interchanging the value, not letting to keep same value in both box.

**Comment by elena-zh** [comment]
> Hey, looks like issue is already resolved. On trying to set same token in to and from input box , it's taking the token in one box and asking to select token in other one and if there are already two different tokens present , it's interchanging the value, not letting to keep same value in both box.

Hey @Wholesomebruh , thank you for checking this. 
Unfortunately, the issue is still reproducible. Please, follow the exact steps in the issue description in order to reproduce it.
