### ISSUE TITLE
[1.53] Missing areas for colors styling

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3522]
- [x] Limit orders page: links are different 
![learn more](https://github.com/cowprotocol/cowswap/assets/70885163/727ca29d-762b-47c0-8d90-2261d33d8d62)

- [x] token selector in the disabled area + tokens with dark icons 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/f6308c28-f9b6-4e6d-8abd-87a82eeae870)

- [x] Invalid name in the recipient field
![image](https://github.com/cowprotocol/cowswap/assets/70885163/4bc7efb4-ce9a-4a76-94ac-68d746a6d226)

- [x] Broken icon on the Approve button, light mode 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/15a7f5e0-a292-48ea-b059-451e89970cbd)

- [x] Terms and conditions link in the dark mode
![terms](https://github.com/cowprotocol/cowswap/assets/70885163/6992e848-2f30-452e-99ac-945c34de6416)

**Comment by anxolin** [comment]
Adding also Terms and conditions link styles

In release: https://swap-dev-git-release-1530-cowswap.vercel.app/#/1/advanced/WETH?tab=open&page=1
![image](https://github.com/cowprotocol/cowswap/assets/2352112/a016d13a-fe44-48f3-a8d8-f62d52273339)

Prod:
![image](https://github.com/cowprotocol/cowswap/assets/2352112/ecd9e027-debf-4548-bf43-482f4902e4c1)

**Comment by alfetopito** [comment]
On TWAP orders table, the executes at table background is now a gradient.

![image](https://github.com/cowprotocol/cowswap/assets/43217/f95a703d-b706-4760-9cea-de29d3bee8f7)

Is this change intentional?
Needs investigation

**Comment by fairlighteth** [comment]
Most items addressed in https://github.com/cowprotocol/cowswap/pull/3566

**Comment by fairlighteth** [comment]
> On TWAP orders table, the executes at table background is now a gradient.
> 
> ![image](https://private-user-images.githubusercontent.com/43217/291880721-f95a703d-b706-4760-9cea-de29d3bee8f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MTk1MTYsIm5iZiI6MTcwNDcxOTIxNiwicGF0aCI6Ii80MzIxNy8yOTE4ODA3MjEtZjk1YTcwM2QtYjcwNi00NzYwLTljZWEtZGUyOWQzYmVlOGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDEzMDY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwODQ4N2RlYmRkZGM3YTY2ODkwZWM4N2Q3NTIyZTk2YWM3ZmZlZTE5YWZjMGY4Yzg2ZDkwMWMzZjJmYmQyODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mCM-XTJ16XIHwzT4KdEOzGXefaAystacDWlK7Ib_1uQ)
> 
> Is this change intentional? Needs investigation

This was intentionally done, mostly to support different color themes. Will review again at some point.

**Comment by elena-zh** [comment]
Hey @fairlighteth , I have updated the issue description and left only not fixed issues here. 
Thanks!

**Comment by fairlighteth** [comment]
@elena-zh can this one be closed?

**Comment by elena-zh** [comment]
@fairlighteth ,sure. I'm wondering why it stopped to be closed automatically with the PR that addresses the issue  :(
